### ISSUE TITLE
Decimal format in dataset measure

### ISSUE THREAD

**Issue by nagyattis81** [eurostat/VTL#2]
Dear developers!

How to setup in number type, the decimal format? 
In this example:

```
define dataset DECIMAL_TEST is
 measure FIELD number;
end dataset;

```

I'd like to store this value in the FIELD  measure : **306655.897583**

Thank you in advance for your help!
aha

**Comment by mpanf** [comment]
Dear nagyattis81,

I think in Hungarian, as in Polish, the decimal part is separated by a comma. In English it is dot.

The problem is that the oracle database has different locale settings than the java environment in which VTL Sandbox was launched.

Solution:
We have forced English settings for the java environment.

java **-Duser.country=en -Duser.language=en** -Xms128m -Xmx512m -jar VTL.jar …

It works fine for this simple dataset:
define dataset dec_test is
identifier	id	integer	;
measure		va	number	;
end dataset;

CSV file with data:
id	va
1	21
2	65
3	68
4	55
5	34
6	49
7	25
8	46
9	49
10	48
11	43
12	44
13	27
14	52
15	30
16	25
17	20
18	61
19	31
20	33
21	42
22	38
23	35
24	26
25	51
26	52
27	65
28	48
29	58
30	123.45
31	306655.897583

I attach sample files.
[decimal_test.zip](https://github.com/eurostat/VTL/files/3515861/decimal_test.zip)

**Comment by capacma** [comment]
OK thanks
In the current version of VTL, the decimal format cannot be indicated in the type of the measure.
